name: Continuous Integration for action server
on:
  push:
    branches:
    - master
    # paths:
    # - 'actions/**'

jobs:
  action_server_job:
    runs-on: ubuntu-latest
    name: Build Rasa Action Server image and upgrade Rasa X deployment
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: My action server image
      uses: RasaHQ/action-server-gha@master
      with: 
        rasa_sdk_version: 1.10
        docker_image_name: 't4grasafamilienlotse1/rasa_familienlotse_action_server'
        actions_directory: 'actions'
        docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
        docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_image_tag: ${{ github.sha}}
    - name: My action server image2
      uses: RasaHQ/action-server-gha@master
      with: 
        rasa_sdk_version: 1.10
        docker_image_name: 't4grasafamilienlotse1/rasa_familienlotse_action_server'
        actions_directory: 'actions'
        docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
        docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_image_tag: latest
